[ISSUE-1045] Fake Attach Feature for Non-LVM-Block-Mode Volumes for OBS Release 1.3 (#1048)
* fix pr validation startup failure



* directly use generated file for fake attach block mode



* still use loopback device wrap



* refine code for creating fake device



* fix go lint error



* add mock func implementation



* fix go lint



* fix UT



* refine func



* support fake attach block mode with fake device, add removeLoopDevice,



* fix go lint



* refine



* support clean fake device in fake-attach block-mode



* support non-existing current fake device case



* change fake device dir on host



* refine log



* support the case of get fake device info failure



* clean fake device also in removal of fake-attach block-mode vol



* if fake-device ann is invalid, re-create the fake device and update ann



* fix



* enhance



* refine



* refine



* add comment



* add UT



* add UT



* add UT



* add UT



* check loop device err shouldn't block subsequent op; clean fake device should also check loop device first



* update fake-attach doc accordingly



* fix typo



* refine doc



---------

Signed-off-by: CraneShiEMC <64512450+CraneShiEMC@users.noreply.github.com>

diff --git a/.github/workflows/pr.yml b/.github/workflows/pr.yml
--- a/.github/workflows/pr.yml
+++ b/.github/workflows/pr.yml
@@ -107,21 +107,23 @@ jobs:
         make install-controller-gen
         make generate-deepcopy
 
-    - name: Verify Changed files
-      uses: tj-actions/verify-changed-files@v5.5
-      id: changed_files
-      with:
-        files: |
-           api/generated/v1/*.go
-           api/v1/*/*.go
-           '.(go)$'
-           
-    - name: Display changed files
-      if: steps.changed_files.outputs.files_changed == 'true'
-      run: |
-        echo "Changed files: ${{ steps.changed_files.outputs.changed_files }}"
-        
-    - name: Perform action when files change.
-      if: steps.changed_files.outputs.files_changed == 'true'
-      run: |
-        exit 1
+# Temporarily comment out the forbidden 3rd-party action script from our github PR validation workflow
+# to fix our github PR validation startup failure.
+#    - name: Verify Changed files
+#      uses: tj-actions/verify-changed-files@v5.5
+#      id: changed_files
+#      with:
+#        files: |
+#           api/generated/v1/*.go
+#           api/v1/*/*.go
+#           '.(go)$'
+#
+#    - name: Display changed files
+#      if: steps.changed_files.outputs.files_changed == 'true'
+#      run: |
+#        echo "Changed files: ${{ steps.changed_files.outputs.changed_files }}"
+#
+#    - name: Perform action when files change.
+#      if: steps.changed_files.outputs.files_changed == 'true'
+#      run: |
+#        exit 1
